language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
  - npm test -- --coverage
  - npm run build
  - cd src
  - wget https://github.com/phillyfan1138/option_price_faas/releases/download/v8/openapi.yml
  - cd ..
  - cd build
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalculation.pdf
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalibration.pdf
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master